services:
  postgres:
    image: 'postgres:15.7'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15432:5432'
  rabbitmq:
    image: 'rabbitmq:3.12.6-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
  redis:
    image: 'redis:7.2.1-alpine'
    ports:
      - '6379:6379'
